# 빌드 단계: Node.js를 사용하여 애플리케이션의 의존성을 설치합니다.
FROM diamol/node AS builder

# 컨테이너 내 작업 디렉토리를 /src로 설정합니다.
WORKDIR /src

# 소스 코드의 package.json 파일을 현재 작업 디렉토리로 복사합니다.
COPY src/package.json .

# npm을 사용하여 의존성을 설치합니다.
RUN npm install

# 실행 단계: 애플리케이션을 실행하기 위한 Node.js 이미지를 사용합니다.
FROM diamol/node

# 컨테이너가 외부와 통신할 포트 80을 엽니다.
EXPOSE 80

# 컨테이너가 시작될 때 실행할 명령어를 지정합니다.
CMD ["node", "server.js"]

# 컨테이너 내 작업 디렉토리를 /app으로 설정합니다.
WORKDIR /app

# 빌드 단계에서 설치된 node_modules를 실행 단계로 복사합니다.
COPY --from=builder /src/node_modules/ /app/node_modules/

# 소스 코드 전체를 /app 디렉토리로 복사합니다.
COPY src/ .
